# -*- coding: utf-8 -*-
"""mycap_ds1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JHNOvt_B8IO0PWNAPe9qMmNg1t2mu2J6
"""

import math
r=float(input(print("Enter the radius of the circle")))
a=math.pi*(r**2)
print("The radius of the circle is : %f"%a)